//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushAirbrush_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushAirbrush_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushBlend_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushBlend_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushBucketFill_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushBucketFill_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushClone_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushClone_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushConvolve_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushConvolve_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushDodgeBurn_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushDodgeBurn_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushEraser_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushEraser_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushHeal_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushHeal_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushInk_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushInk_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushPaintbrush_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushPaintbrush_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushPencil_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushPencil_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushPerspectiveClone_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushPerspectiveClone_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_BrushSmudge_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_BrushSmudge_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_ColourBrightnessContrast_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_ColourBrightnessContrast_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_ColourColourBalance_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_ColourColourBalance_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_ColourColourize_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_ColourColourize_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_ColourCurves_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_ColourCurves_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_ColourDesaturate_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_ColourDesaturate_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_ColourLevels_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_ColourLevels_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_ColourPickerTool_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_ColourPickerTool_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_ColourPosterize_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_ColourPosterize_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_ColourThreshold_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_ColourThreshold_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_GEGLOperationTool_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_GEGLOperationTool_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_MagnifyTool_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_MagnifyTool_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_MeasureTool_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_MeasureTool_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_PathTool_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_PathTool_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_SelectionByColor_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_SelectionByColor_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_SelectionEllipse_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_SelectionEllipse_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_SelectionForeground_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_SelectionForeground_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_SelectionLasso_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_SelectionLasso_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_SelectionRectangle_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_SelectionRectangle_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_SelectionScissors_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_SelectionScissors_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_SelectionWand_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_SelectionWand_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_TextTool_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_TextTool_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_TransformAlign_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_TransformAlign_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_TransformCrop_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_TransformCrop_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_TransformFlip_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_TransformFlip_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_TransformMove_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_TransformMove_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_TransformPerspective_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_TransformPerspective_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_TransformRotate_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_TransformRotate_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_TransformScale_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_TransformScale_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIMP_Toolbox_TransformShear_Icon {
            get {
                object obj = ResourceManager.GetObject("GIMP_Toolbox_TransformShear_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap standardcolors {
            get {
                object obj = ResourceManager.GetObject("standardcolors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switchcolors {
            get {
                object obj = ResourceManager.GetObject("switchcolors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
